spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payments
    username: root
    password: SuperAbc123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    rest:
      base-path: /api

